Adapted from https://github.com/estimate/pandas-exercises, if you need the 81 MB `P00000001-ALL.txt` file, grab it there

In [38]:
from pandas import *
import matplotlib as mpl
mpl.rc('figure', figsize=(12, 6))
options.display.max_columns = 18
months = {'JAN' : 1, 'FEB' : 2, 'MAR' : 3, 'APR' : 4, 'MAY' : 5, 'JUN' : 6,
          'JUL' : 7, 'AUG' : 8, 'SEP' : 9, 'OCT': 10, 'NOV': 11, 'DEC' : 12}
of_interest = ['Obama, Barack', 'Romney, Mitt', 'Santorum, Rick', 
               'Paul, Ron', 'Gingrich, Newt']
parties = {
  'Bachmann, Michelle': 'Republican',
  'Romney, Mitt': 'Republican',
  'Obama, Barack': 'Democrat',
  "Roemer, Charles E. 'Buddy' III": 'Reform',
  'Pawlenty, Timothy': 'Republican',
  'Johnson, Gary Earl': 'Libertarian',
  'Paul, Ron': 'Republican',
  'Santorum, Rick': 'Republican',
  'Cain, Herman': 'Republican',
  'Gingrich, Newt': 'Republican',
  'McCotter, Thaddeus G': 'Republican',
  'Huntsman, Jon': 'Republican',
  'Perry, Rick': 'Republican'           
 }

In [39]:
fec = read_csv('P00000001-ALL.txt')

In [40]:
fec

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,3.6601e+08,RETIRED,RETIRED,250.0,20-JUN-11,NaN,NaN,NaN,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,3.6601e+08,RETIRED,RETIRED,50.0,23-JUN-11,NaN,NaN,NaN,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,3.68633e+08,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-JUL-11,NaN,NaN,NaN,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,7.24548e+08,NONE,RETIRED,250.0,01-AUG-11,NaN,NaN,NaN,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,7.19016e+08,NONE,RETIRED,300.0,20-JUN-11,NaN,NaN,NaN,SA17A,736166
5,C00410118,P20002978,"Bachmann, Michelle","BECKMAN, JAMES",SPRINGDALE,AR,7.27647e+08,NONE,RETIRED,500.0,23-JUN-11,NaN,NaN,NaN,SA17A,736166
6,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,7.24548e+08,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,21-JUN-11,NaN,NaN,NaN,SA17A,736166
7,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,7.24548e+08,NONE,RETIRED,250.0,05-JUL-11,NaN,NaN,NaN,SA17A,749073
8,C00410118,P20002978,"Bachmann, Michelle","COLLINS, SARAH",MESA,AZ,8.52107e+08,ST. JOSEPH HOSPITAL,RN,250.0,21-JUN-11,NaN,NaN,NaN,SA17A,736166
9,C00410118,P20002978,"Bachmann, Michelle","COLEMAN, RONALD",TUCSON,AZ,8.57499e+08,RAYTHEON,ELECTRICAL ENGINEER,250.0,20-JUN-11,NaN,NaN,NaN,SA17A,736166
10,C00410118,P20002978,"Bachmann, Michelle","ATCHLEY, JR, KEITH",MESA,AZ,85215,NONE,RETIRED,250.0,22-JUN-11,NaN,NaN,NaN,SA17A,736166
11,C00410118,P20002978,"Bachmann, Michelle","FARNSWORTH, ROSS",MESA,AZ,8.52062e+08,FARNSWORTH COMPANIES,LAND DEVELOPER,500.0,22-JUN-11,NaN,NaN,NaN,SA17A,736166
12,C00410118,P20002978,"Bachmann, Michelle","PRESTON, CLIFFORD",ORO VALLEY,AZ,8.57379e+08,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,21-JUN-11,NaN,NaN,NaN,SA17A,736166
13,C00410118,P20002978,"Bachmann, Michelle","WILSON, RICHARD",FLAGSTAFF,AZ,8.60011e+08,NONE,RETIRED,500.0,17-JUN-11,NaN,NaN,NaN,SA17A,736166
14,C00410118,P20002978,"Bachmann, Michelle","MILLER, WILLIAM",SCOTTSDALE,AZ,8.52513e+08,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,11-JUL-11,NaN,NaN,NaN,SA17A,749073
15,C00410118,P20002978,"Bachmann, Michelle","DOLAN, WILLIAM",PHOENIX,AZ,8.50145e+08,VA MEDICAL CENTER,PHYSICIAN,300.0,08-JUL-11,NaN,NaN,NaN,SA17A,749073
16,C00410118,P20002978,"Bachmann, Michelle","REULING, RICHARD",GREEN VALLEY,AZ,8.56225e+08,NONE,RETIRED,1000.0,05-JUL-11,NaN,NaN,NaN,SA17A,749073
17,C00410118,P20002978,"Bachmann, Michelle","PETERSEN, W",GILBERT,AZ,85295,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,27-JUN-11,NaN,NaN,NaN,SA17A,736166
18,C00410118,P20002978,"Bachmann, Michelle","ALLUMBAUGH, KATHY",SANTA ANA,CA,9.27051e+08,NONE,RETIRED,250.0,13-JUN-11,NaN,NaN,NaN,SA17A,736166
19,C00410118,P20002978,"Bachmann, Michelle","DEL POZO, JOSE",DEL MAR,CA,9.20143e+08,RETIRES,RETIRED,300.0,16-JUN-11,NaN,NaN,NaN,SA17A,736166
20,C00410118,P20002978,"Bachmann, Michelle","KIEFFER, PIERRE",SACRAMENTO,CA,9.58257e+08,SELF,OFFICE FURNITURE BROKER,500.0,16-JUN-11,NaN,NaN,NaN,SA17A,736166
21,C00410118,P20002978,"Bachmann, Michelle","HANNAH, STEPHEN",SHERMAN OAKS,CA,9.14132e+08,RETIRED,RETIRED,250.0,16-JUN-11,NaN,NaN,NaN,SA17A,736166
22,C00410118,P20002978,"Bachmann, Michelle","MINNIS, RITA",MILPITAS,CA,9.50358e+08,MILPITS MATERIALS,MANAGER,2500.0,17-JUN-11,NaN,NaN,NaN,SA17A,736166
23,C00410118,P20002978,"Bachmann, Michelle","MINNIS, RITA",MILPITAS,CA,9.50358e+08,MILPITS MATERIALS,MANAGER,2500.0,17-JUN-11,NaN,NaN,NaN,SA17A,736166
24,C00410118,P20002978,"Bachmann, Michelle","BOSTON, JOYCE",RANCHO CUCAMONGA,CA,9.17305e+08,INFORMATION REQUESTED,INFORMATION REQUESTED,300.0,18-JUL-11,NaN,NaN,NaN,SA17A,749073
25,C00410118,P20002978,"Bachmann, Michelle","MANSFIELD, LORNA",WALNUT CREEK,CA,9.45952e+08,NONE,RETIRED,100.0,18-JUL-11,NaN,NaN,NaN,SA17A,749073
26,C00410118,P20002978,"Bachmann, Michelle","EDWARDS, MARK",LA JOLLA,CA,9.20378e+08,NONE,RETIRED,150.0,05-AUG-11,NaN,NaN,NaN,SA17A,749073
27,C00410118,P20002978,"Bachmann, Michelle","PECONI, GIANFRANCO",CEDAR GLEN,CA,9.23211e+08,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,01-JUL-11,NaN,NaN,NaN,SA17A,749073
28,C00410118,P20002978,"Bachmann, Michelle","WILSON, CAROL R.",LINCOLN,CA,9.56488e+08,NONE,RETIRED,500.0,05-JUL-11,NaN,NaN,NaN,SA17A,749073
29,C00410118,P20002978,"Bachmann, Michelle","CASTAGNOZZI, MARY",PIEDMONT,CA,9.46114e+08,PIEDMONT LAUNGUAGE SCHOOL,MANDARIN TEACHER,250.0,05-JUL-11,NaN,NaN,NaN,SA17A,749073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536011,C00500587,P20003281,"Perry, Rick","ZATEZALO, DAVID G. MR.",WHEELING,WV,260036639,RHINO RESOURCES,COAL MINER,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536012,C00500587,P20003281,"Perry, Rick","THALMAN, FRANK E. MR.",WHEELING,WV,260031672,WARWOOD ARMATURE REPAIR COMPANY,VICE PRESIDENT,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536013,C00500587,P20003281,"Perry, Rick","THALMAN, RAYMOND V. MR. III",WHEELING,WV,260030401,WARWOOD ARMATURE REPAIR COMPANY,PRESIDENT,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536014,C00500587,P20003281,"Perry, Rick","TEMPLIN, JOE MR.",WHEELING,WV,260034922,THE OHIO VALLEY COAL COMPANY,MANAGER OF INFORMATION SYSTEMS,250.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536015,C00500587,P20003281,"Perry, Rick","WOISNET, JILL MRS.",MORGANTOWN,WV,265088649,SWANSON INDUSTRIES INC,VP,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536016,C00500587,P20003281,"Perry, Rick","WOISNET, LEX MR.",MORGANTOWN,WV,265088649,SWANSON INDUSTRIES INC.,PURCHASING MANAGER,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536017,C00500587,P20003281,"Perry, Rick","WHITT, RICHARD P. MR.",WHEELING,WV,260036021,IVALDET LABORATORIES,EXECUTIVE,300.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536018,C00500587,P20003281,"Perry, Rick","WHITESCARVER, IDALEE MRS.",GRAFTON,WV,263549310,QUALITY HYDRAULICS INC.,SECRETARY TO VICE PRESIDENT,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536019,C00500587,P20003281,"Perry, Rick","WHITESCARVER, JOHN E. MR.",GRAFTON,WV,263549310,QUALITY HYDRAULICS INC.,PRESIDENT/TREASURER,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536020,C00500587,P20003281,"Perry, Rick","FRIESS, STEPHEN MR.",JACKSON,WY,830021655,FRIESS INC.,CONSULTANT,1000.0,29-SEP-11,NaN,NaN,NaN,SA17A,751678
536021,C00500587,P20003281,"Perry, Rick","HANSEN, STEVE MR.",CHEYENNE,WY,820013163,TEXAS ENERGY LLC,EXECUTIVE,250.0,15-NOV-11,NaN,X,SEE ATTRIBUTION,SA17A,761750
536022,C00500587,P20003281,"Perry, Rick","HARDER, ROBERT",POWELL,WY,824359238,NaN,RETIRED,100.0,29-OCT-11,NaN,NaN,NaN,SA17A,761750
536023,C00500587,P20003281,"Perry, Rick","HARDER, ROBERT",POWELL,WY,824359238,NaN,RETIRED,100.0,12-NOV-11,NaN,NaN,NaN,SA17A,761750
536024,C00500587,P20003281,"Perry, Rick","HARDER, ROBERT",POWELL,WY,824359238,NaN,RETIRED,100.0,30-NOV-11,NaN,NaN,NaN,SA17A,761750
536025,C00500587,P20003281,"Perry, Rick","KINSEY, JOAN",LARAMIE,WY,820709758,RETIRED,RETIRED,1000.0,17-AUG-11,NaN,NaN,NaN,SA17A,751678
536026,C00500587,P20003281,"Perry, Rick","SUGDEN, SUSAN MRS.",JACKSON,WY,830010489,SELF-EMPLOYED,INVESTOR,2500.0,26-AUG-11,NaN,NaN,NaN,SA17A,751678
536027,C00500587,P20003281,"Perry, Rick","LUCAS, WES",TETON VILLAGE,WY,83025,SIRVA,CEO,2500.0,04-OCT-11,NaN,NaN,NaN,SA17A,761750
536028,C00500587,P20003281,"Perry, Rick","LUCAS, ELISABET",TETON VILLAGE,WY,830250824,LUCAS PROPERTIES,OWNER,2500.0,04-OCT-11,NaN,NaN,NaN,SA17A,761750
536029,C00500587,P20003281,"Perry, Rick",TEXAS ENERGY L.L.C.,CHEYENNE,WY,820013163,LLC,LLC,250.0,30-SEP-11,NaN,X,SEE ATTRIBUTION BELOW,SA17A,761750
536030,C00500587,P20003281,"Perry, Rick","SPENCE, RUSSELL",RIVERTON,WY,825019711,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,250.0,15-AUG-11,NaN,NaN,NaN,SA17A,751678
536031,C00500587,P20003281,"Perry, Rick",TEXAS ENERGY L.L.C.,CHEYENNE,WY,820013163,NaN,NaN,250.0,30-SEP-11,NaN,NaN,ATTRIBUTION TO PARTNERS REQUESTED,SA17A,751678
536032,C00500587,P20003281,"Perry, Rick","SUGDEN, RICHARD G. MR.",JACKSON,WY,830010489,FAMILY PRACTICE ASSOCIATES,DOCTOR,2500.0,26-AUG-11,NaN,NaN,NaN,SA17A,751678
536033,C00500587,P20003281,"Perry, Rick","HARDER, ROBERT",POWELL,WY,824359238,NaN,RETIRED,100.0,01-OCT-11,NaN,NaN,NaN,SA17A,761750
536034,C00500587,P20003281,"Perry, Rick","ELWOOD, MIKE MR.",INFO REQUESTED,XX,99999,AM COAL,ENGINEER,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536035,C00500587,P20003281,"Perry, Rick","HEFFERNAN, JILL PRINCE MRS.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536036,C00500587,P20003281,"Perry, Rick","ANDERSON, MARILEE MRS.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,2500.0,31-AUG-11,NaN,NaN,NaN,SA17A,751678
536037,C00500587,P20003281,"Perry, Rick","TOLBERT, DARYL MR.",INFO REQUESTED,XX,99999,T.A.C.C.,LONGWALL MAINTENANCE FOREMAN,500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536038,C00500587,P20003281,"Perry, Rick","GRANE, BRYAN F. MR.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,500.0,29-SEP-11,NaN,NaN,NaN,SA17A,751678
536039,C00500587,P20003281,"Perry, Rick","DUFFY, DAVID A. MR.",INFO REQUESTED,XX,99999,DUFFY EQUIPMENT COMPANY INC.,BUSINESS OWNER,2500.0,30-SEP-11,NaN,NaN,NaN,SA17A,751678
536040,C00500587,P20003281,"Perry, Rick","GORMAN, CHRIS D. MR.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,5000.0,29-SEP-11,REATTRIBUTION / REDESIGNATION REQUESTED (AUTOM...,NaN,REATTRIBUTION / REDESIGNATION REQUESTED (AUTOM...,SA17A,751678

In [41]:
parties    # dictionary

{'Bachmann, Michelle': 'Republican',
 'Cain, Herman': 'Republican',
 'Gingrich, Newt': 'Republican',
 'Huntsman, Jon': 'Republican',
 'Johnson, Gary Earl': 'Libertarian',
 'McCotter, Thaddeus G': 'Republican',
 'Obama, Barack': 'Democrat',
 'Paul, Ron': 'Republican',
 'Pawlenty, Timothy': 'Republican',
 'Perry, Rick': 'Republican',
 "Roemer, Charles E. 'Buddy' III": 'Reform',
 'Romney, Mitt': 'Republican',
 'Santorum, Rick': 'Republican'}

In [42]:
fec.cand_nm

0         Bachmann, Michelle
1         Bachmann, Michelle
2         Bachmann, Michelle
3         Bachmann, Michelle
4         Bachmann, Michelle
5         Bachmann, Michelle
6         Bachmann, Michelle
7         Bachmann, Michelle
8         Bachmann, Michelle
9         Bachmann, Michelle
10        Bachmann, Michelle
11        Bachmann, Michelle
12        Bachmann, Michelle
13        Bachmann, Michelle
14        Bachmann, Michelle
15        Bachmann, Michelle
16        Bachmann, Michelle
17        Bachmann, Michelle
18        Bachmann, Michelle
19        Bachmann, Michelle
20        Bachmann, Michelle
21        Bachmann, Michelle
22        Bachmann, Michelle
23        Bachmann, Michelle
24        Bachmann, Michelle
25        Bachmann, Michelle
26        Bachmann, Michelle
27        Bachmann, Michelle
28        Bachmann, Michelle
29        Bachmann, Michelle
                 ...
536011           Perry, Rick
536012           Perry, Rick
536013           Perry, Rick
536014           Perry, Rick
536015           Perry, Rick
536016           Perry, Rick
536017           Perry, Rick
536018           Perry, Rick
536019           Perry, Rick
536020           Perry, Rick
536021           Perry, Rick
536022           Perry, Rick
536023           Perry, Rick
536024           Perry, Rick
536025           Perry, Rick
536026           Perry, Rick
536027           Perry, Rick
536028           Perry, Rick
536029           Perry, Rick
536030           Perry, Rick
536031           Perry, Rick
536032           Perry, Rick
536033           Perry, Rick
536034           Perry, Rick
536035           Perry, Rick
536036           Perry, Rick
536037           Perry, Rick
536038           Perry, Rick
536039           Perry, Rick
536040           Perry, Rick
Name: cand_nm, dtype: object

In [43]:
fec['party'] = fec.cand_nm.map(parties)  # map can take dictionary, series... 
                                         # Alternatively, use list comprehension: [parties[x] for x in fec.cand_nm]

In [44]:
fec.ix[0]    # A single record.

cmte_id                       C00410118
cand_id                       P20002978
cand_nm              Bachmann, Michelle
contbr_nm               HARVEY, WILLIAM
contbr_city                      MOBILE
contbr_st                            AL
contbr_zip                   3.6601e+08
contbr_employer                 RETIRED
contbr_occupation               RETIRED
contb_receipt_amt                   250
contb_receipt_dt              20-JUN-11
receipt_desc                        NaN
memo_cd                             NaN
memo_text                           NaN
form_tp                           SA17A
file_num                         736166
party                        Republican
Name: 0, dtype: object

In [45]:
fec.party.value_counts()   # Doing it high level way using histogram.

Democrat       292400
Republican     237575
Reform           5364
Libertarian       702
Name: party, dtype: int64

In [46]:
np.unique(fec.party)

array(['Democrat', 'Libertarian', 'Reform', 'Republican'], dtype=object)

In [47]:
fec.groupby('party')['contb_receipt_amt'].sum()

party
Democrat       8.105758e+07
Libertarian    4.132769e+05
Reform         3.390338e+05
Republican     1.192255e+08
Name: contb_receipt_amt, dtype: float64

In [48]:
fec.groupby(['party', 'contb_receipt_dt'])['contb_receipt_amt'].sum()   # Not a python date object.

party       contb_receipt_dt
Democrat    01-AUG-11            175281.00
            01-DEC-11            651532.82
            01-JAN-12             58098.80
            01-JUL-11            165961.00
            01-JUN-11            145459.00
            01-MAY-11             82644.00
            01-NOV-11            122529.87
            01-OCT-11            148977.00
            01-SEP-11            403297.62
            02-AUG-11            164510.11
            02-DEC-11            216056.96
            02-JAN-12             89743.60
            02-JUL-11             17105.00
            02-JUN-11            422453.00
            02-MAY-11            396675.00
            02-NOV-11            147183.81
            02-OCT-11             62605.62
            02-SEP-11            137948.41
            03-AUG-11            147053.02
            03-DEC-11             81304.02
            03-JAN-12             87406.97
            03-JUL-11              5982.00
            03-JUN-11            320176.20
            03-MAY-11            261819.11
            03-NOV-11            119304.56
            03-OCT-11            363061.02
            03-SEP-11             45598.00
            04-APR-11            640235.12
            04-AUG-11            598784.23
            04-DEC-11             72795.10
                                   ...
Republican  29-AUG-11            941769.23
            29-DEC-11            428501.42
            29-JAN-11               750.00
            29-JAN-12             75220.02
            29-JUL-11            233423.35
            29-JUN-11           1340704.29
            29-MAR-11             38875.00
            29-MAY-11              8363.20
            29-NOV-11            407322.64
            29-OCT-11             81924.01
            29-SEP-11           1612794.52
            30-APR-11             43004.80
            30-AUG-11            915548.58
            30-DEC-11            492470.45
            30-JAN-12            255204.80
            30-JUL-11             12249.04
            30-JUN-11           2744932.63
            30-MAR-11             50240.00
            30-MAY-11             17803.60
            30-NOV-11            809014.83
            30-OCT-11             43913.16
            30-SEP-11           4886331.76
            31-AUG-11           1017735.02
            31-DEC-11           1094376.72
            31-JAN-11              6000.00
            31-JAN-12            869890.41
            31-JUL-11             12781.02
            31-MAR-11             62475.00
            31-MAY-11            301339.80
            31-OCT-11            734601.83
Name: contb_receipt_amt, dtype: float64

In [49]:
fec.contb_receipt_dt[0]

'20-JUN-11'

In [50]:
print months

{'FEB': 2, 'AUG': 8, 'JAN': 1, 'DEC': 12, 'OCT': 10, 'MAR': 3, 'SEP': 9, 'MAY': 5, 'JUN': 6, 'JUL': 7, 'APR': 4, 'NOV': 11}

In [51]:
def convert_date(val):    # function to convert date to python's date object.
    d, m, y = val.split('-')
    m = months[m]
    return datetime(int ('20' + y), m, int(d))

fec.contb_receipt_dt   # output a list of date (not yet in python objects).
fec['contb_receipt_dt'] = fec.contb_receipt_dt.map(convert_date)

In [52]:
fec.contb_receipt_dt[0]

Timestamp('2011-06-20 00:00:00')

In [53]:
fec.groupby(['party', 'contb_receipt_dt'])['contb_receipt_amt'].sum() # Same as above, however, date converted to python object.

party       contb_receipt_dt
Democrat    2011-04-04           640235.12
            2011-04-05           307641.00
            2011-04-06           247542.59
            2011-04-07           252336.00
            2011-04-08           295452.00
            2011-04-09           105879.00
            2011-04-10           100373.00
            2011-04-11           360728.00
            2011-04-12           405160.46
            2011-04-13           382836.33
            2011-04-14           306643.50
            2011-04-15           408377.00
            2011-04-16            82658.00
            2011-04-17            70802.00
            2011-04-18           501971.37
            2011-04-19           304874.00
            2011-04-20           314540.11
            2011-04-21           315618.00
            2011-04-22           295464.45
            2011-04-23            34829.00
            2011-04-24            37100.00
            2011-04-25           447282.00
            2011-04-26           600960.50
            2011-04-27           188595.00
            2011-04-28           677041.36
            2011-04-29           294709.00
            2011-04-30            95582.00
            2011-05-01            82644.00
            2011-05-02           396675.00
            2011-05-03           261819.11
                                   ...
Republican  2012-01-02           114037.13
            2012-01-03           155803.62
            2012-01-04           577733.61
            2012-01-05           451065.98
            2012-01-06           262798.46
            2012-01-07           148145.58
            2012-01-08            84342.84
            2012-01-09           501931.44
            2012-01-10           487901.67
            2012-01-11           452916.99
            2012-01-12           348327.39
            2012-01-13           463368.26
            2012-01-14           608470.68
            2012-01-15           322194.08
            2012-01-16           367791.70
            2012-01-17           625365.77
            2012-01-18           888681.17
            2012-01-19          1066250.23
            2012-01-20           401298.03
            2012-01-21           374261.81
            2012-01-22           507168.71
            2012-01-23           645477.15
            2012-01-24           462233.66
            2012-01-25           416931.39
            2012-01-26           256406.86
            2012-01-27           368441.82
            2012-01-28            82775.80
            2012-01-29            75220.02
            2012-01-30           255204.80
            2012-01-31           869890.41
Name: contb_receipt_amt, dtype: float64

In [54]:
by_date = fec.groupby(['party', 'contb_receipt_dt'])['contb_receipt_amt'].sum()

In [55]:
by_date.unstack('party')   # Indexes are dates. Columns are political parties.

party               Democrat  Libertarian    Reform  Republican
contb_receipt_dt
2011-01-01               NaN          NaN       NaN     8600.00
2011-01-03               NaN          NaN       NaN     4800.00
2011-01-04               NaN          NaN       NaN     5000.00
2011-01-12               NaN          NaN       NaN     4150.00
2011-01-13               NaN          NaN       NaN     4000.00
2011-01-14               NaN          NaN       NaN     6000.00
2011-01-15               NaN          NaN       NaN      500.00
2011-01-16               NaN          NaN       NaN      750.00
2011-01-17               NaN          NaN       NaN      500.00
2011-01-18               NaN          NaN       NaN     4800.00
2011-01-20               NaN          NaN       NaN     2650.00
2011-01-21               NaN          NaN       NaN      250.00
2011-01-22               NaN          NaN       NaN      250.00
2011-01-24               NaN          NaN       NaN     2400.00
2011-01-26               NaN          NaN       NaN     5400.00
2011-01-27               NaN          NaN       NaN     2650.00
2011-01-28               NaN          NaN       NaN      650.00
2011-01-29               NaN          NaN       NaN      750.00
2011-01-31               NaN          NaN       NaN     6000.00
2011-02-01               NaN          NaN       NaN      250.00
2011-02-03               NaN          NaN       NaN     3250.00
2011-02-04               NaN          NaN       NaN     1000.00
2011-02-07               NaN          NaN       NaN     9300.00
2011-02-08               NaN          NaN       NaN     3000.00
2011-02-09               NaN          NaN       NaN     6550.00
2011-02-10               NaN          NaN       NaN      250.00
2011-02-11               NaN          NaN       NaN      250.00
2011-02-12               NaN          NaN       NaN      250.00
2011-02-13               NaN          NaN       NaN      250.00
2011-02-14               NaN          NaN       NaN     2500.00
...                      ...          ...       ...         ...
2012-01-02          89743.60          NaN   2437.13   114037.13
2012-01-03          87406.97          NaN   4006.32   155803.62
2012-01-04         166547.24          NaN   3445.80   577733.61
2012-01-05         198224.86          NaN   3925.48   451065.98
2012-01-06         138822.95          NaN  12676.24   262798.46
2012-01-07          91161.12          NaN   4201.12   148145.58
2012-01-08          81758.00          NaN   3457.52    84342.84
2012-01-09         206996.99          NaN   1950.00   501931.44
2012-01-10         191988.12          NaN   2195.00   487901.67
2012-01-11         185823.52          NaN    945.00   452916.99
2012-01-12         467212.53          NaN    625.00   348327.39
2012-01-13         374570.48          NaN    351.00   463368.26
2012-01-14          81687.80          NaN    200.00   608470.68
2012-01-15          72983.50          NaN    400.00   322194.08
2012-01-16         117163.21          NaN    400.00   367791.70
2012-01-17         298246.61          NaN     40.00   625365.77
2012-01-18         219002.47          NaN       NaN   888681.17
2012-01-19         275532.88          NaN     65.00  1066250.23
2012-01-20         245166.57          NaN    386.00   401298.03
2012-01-21          18513.50          NaN    280.00   374261.81
2012-01-22          67194.23          NaN    450.00   507168.71
2012-01-23         337307.07          NaN    225.00   645477.15
2012-01-24         458909.23          NaN    500.00   462233.66
2012-01-25         438949.32          NaN    282.00   416931.39
2012-01-26         450268.94          NaN     25.00   256406.86
2012-01-27         305785.47          NaN   3176.37   368441.82
2012-01-28         235492.85          NaN    175.00    82775.80
2012-01-29          93177.00          NaN    200.00    75220.02
2012-01-30         435921.72          NaN    130.00   255204.80
2012-01-31        1418410.31          NaN    150.00   869890.41

[376 rows x 4 columns]

In [56]:
by_date.unstack('party').cumsum().plot()

In [57]:
s = by_date.unstack('party')[-5:].stack()

In [58]:
s    # Note the inner level indexes. Not every date has 3 parties. Top level indexes are dates. stack() makes 1 dimensional.
     # Labels propagated down for all 3 observations: political parties.

contb_receipt_dt  party
2012-01-27        Democrat       305785.47
                  Reform           3176.37
                  Republican     368441.82
2012-01-28        Democrat       235492.85
                  Reform            175.00
                  Republican      82775.80
2012-01-29        Democrat        93177.00
                  Reform            200.00
                  Republican      75220.02
2012-01-30        Democrat       435921.72
                  Reform            130.00
                  Republican     255204.80
2012-01-31        Democrat      1418410.31
                  Reform            150.00
                  Republican     869890.41
dtype: float64

In [59]:
s.unstack()    # unstack() 2 dimensional.

party               Democrat   Reform  Republican
contb_receipt_dt
2012-01-27         305785.47  3176.37   368441.82
2012-01-28         235492.85   175.00    82775.80
2012-01-29          93177.00   200.00    75220.02
2012-01-30         435921.72   130.00   255204.80
2012-01-31        1418410.31   150.00   869890.41

In [60]:
s.unstack().stack()  # 2 dimensional to 1 dimensional

contb_receipt_dt  party
2012-01-27        Democrat       305785.47
                  Reform           3176.37
                  Republican     368441.82
2012-01-28        Democrat       235492.85
                  Reform            175.00
                  Republican      82775.80
2012-01-29        Democrat        93177.00
                  Reform            200.00
                  Republican      75220.02
2012-01-30        Democrat       435921.72
                  Reform            130.00
                  Republican     255204.80
2012-01-31        Democrat      1418410.31
                  Reform            150.00
                  Republican     869890.41
dtype: float64

In [61]:
df = s.unstack('party')   # data frame

In [62]:
s.unstack('contb_receipt_dt')

contb_receipt_dt  2012-01-27  2012-01-28  2012-01-29  2012-01-30  2012-01-31
party
Democrat           305785.47   235492.85    93177.00   435921.72  1418410.31
Reform               3176.37      175.00      200.00      130.00      150.00
Republican         368441.82    82775.80    75220.02   255204.80   869890.41

In [63]:
concat([df, df], axis=1, keys=['A', 'B'])  # join 2 copies of data frame.
                                           # standard hierarchical indexing stuff.

                           A                               B           \
party               Democrat   Reform Republican    Democrat   Reform
contb_receipt_dt
2012-01-27         305785.47  3176.37  368441.82   305785.47  3176.37
2012-01-28         235492.85   175.00   82775.80   235492.85   175.00
2012-01-29          93177.00   200.00   75220.02    93177.00   200.00
2012-01-30         435921.72   130.00  255204.80   435921.72   130.00
2012-01-31        1418410.31   150.00  869890.41  1418410.31   150.00


party            Republican
contb_receipt_dt
2012-01-27        368441.82
2012-01-28         82775.80
2012-01-29         75220.02
2012-01-30        255204.80
2012-01-31        869890.41

In [64]:
concat([df, df], axis=1, keys=['A', 'B'])['A']   # select out columns by the first key 'A'. Or select out the 'B' group.conc

party               Democrat   Reform  Republican
contb_receipt_dt
2012-01-27         305785.47  3176.37   368441.82
2012-01-28         235492.85   175.00    82775.80
2012-01-29          93177.00   200.00    75220.02
2012-01-30         435921.72   130.00   255204.80
2012-01-31        1418410.31   150.00   869890.41

In [65]:
concat([df, df], axis=1, keys=['A', 'B']).stack('party')

                                      A           B
contb_receipt_dt party
2012-01-27       Democrat     305785.47   305785.47
                 Reform         3176.37     3176.37
                 Republican   368441.82   368441.82
2012-01-28       Democrat     235492.85   235492.85
                 Reform          175.00      175.00
                 Republican    82775.80    82775.80
2012-01-29       Democrat      93177.00    93177.00
                 Reform          200.00      200.00
                 Republican    75220.02    75220.02
2012-01-30       Democrat     435921.72   435921.72
                 Reform          130.00      130.00
                 Republican   255204.80   255204.80
2012-01-31       Democrat    1418410.31  1418410.31
                 Reform          150.00      150.00
                 Republican   869890.41   869890.41

In [66]:
concat([df, df], axis=1, keys=['A', 'B']).stack(0)  # The group indexes have no labels.

party                 Democrat   Reform  Republican
contb_receipt_dt
2012-01-27       A   305785.47  3176.37   368441.82
                 B   305785.47  3176.37   368441.82
2012-01-28       A   235492.85   175.00    82775.80
                 B   235492.85   175.00    82775.80
2012-01-29       A    93177.00   200.00    75220.02
                 B    93177.00   200.00    75220.02
2012-01-30       A   435921.72   130.00   255204.80
                 B   435921.72   130.00   255204.80
2012-01-31       A  1418410.31   150.00   869890.41
                 B  1418410.31   150.00   869890.41

In [67]:
result = fec.groupby(['cand_nm', 'contbr_occupation'])['contb_receipt_amt'].sum()   # Top contributors to candidates by occupation.

In [68]:
result  # is a data frame instead of series.

cand_nm             contbr_occupation
Bachmann, Michelle  100% DISABLED VETERAN              1869.50
                    100% DISABLED VIETNAM VETERAN       236.25
                    A/C AND HEAT                        250.00
                    ACADEMIC EMPLOYMENT SPECIALIST       25.00
                    ACCOUNT                              50.00
                    ACCOUNT ANALYST                     200.00
                    ACCOUNT EXECUTIVE                   100.00
                    ACCOUNT MANAGER                     230.00
                    ACCOUNTANT                        12979.00
                    ACCOUNTANT TRAINER                  250.00
                    ACCOUNTING                          350.00
                    ACCOUNTING MANAGER                   50.00
                    ACCOUNTING SPECIALIST               250.00
                    ACCOUNTING SUPERVISOR               125.00
                    ACCOUNTING/AUDITING                 700.00
                    ACTIVE DUTY MILITARY                125.00
                    ACTRESS                             601.00
                    ACTUARY                            1050.00
                    AD EXEC                             401.00
                    ADJURET ASST. PROF                   31.00
                    ADJUSTER                            250.00
                    ADMIN. ASSISTANT                    250.00
                    ADMINISNATIVE ASST                  125.00
                    ADMINISTRATION                     1245.00
                    ADMINISTRATIVE ASSISTANT            300.00
                    ADMINISTRATIVE EXECUTIVE            200.00
                    ADMINISTRATIVE LAW JUDGE            575.00
                    ADMINISTRATIVE MED PRAC             100.00
                    ADMINISTRATOR                      4587.00
                    ADMINSTRATOR                        300.00
                                                        ...
Santorum, Rick      WEB COMM. MANAGER                  1000.00
                    WEB DESIGN                          500.00
                    WEB DESIGNER                        235.00
                    WEBMASTER                           250.00
                    WELD ENGINEER                      1000.00
                    WELDER                              250.00
                    WELL BEING                          250.00
                    WELL BEING COORDINATOR              300.00
                    WELLBORN CABINET INC.               500.00
                    WHEATON COLLEGE (IL) STUDENT        250.00
                    WHOLESALE MFG                       400.00
                    WIDOW                                80.00
                    WIFE AND MOTHER                    1500.00
                    WIFE AND MOTHER (AT HOME)           100.00
                    WIFE MOTHER TEACHER                1000.00
                    WILDLIFE REFUGE MANAGER             200.00
                    WIND FARM DEVELOPER                 400.00
                    WINDOW CLEANER                       85.00
                    WINERY                              300.00
                    WIRELESS NETWORK ENGINEER           220.15
                    WITHHELD                           1000.00
                    WNG                                 700.00
                    WORKER II                           300.00
                    WRITER                             4894.55
                    WRITER ACTIVIST                    1112.00
                    WRITER EDITOR                       250.00
                    WRITER/ACCOUNT EXEC                 500.00
                    WRITER/JOURNALIST                   250.00
                    WRITER/LAWYER                       300.00
                    YOUTH MINISTER                      250.00
Name: contb_receipt_amt, dtype: float64

In [69]:
result[:, 'ZOMBIE SLAYER']

cand_nm
Paul, Ron    1556.0
Name: contb_receipt_amt, dtype: float64

In [70]:
result = fec.groupby(['cand_nm', 'contbr_occupation']).sum()  # When doing this aggregation, we don't need to select the columns as above.
# There are columns that are not possible to sum. The code actually tries to sum them all: nuisance columns. Whenever it fails, it just silently drops them out.

In [71]:
result = result.reset_index()  # opposite of set_index(). Took 'cand_nm' and 'contbr_occupation' and set them as col indexes again, so that the indexes are just simple integer indexes.

In [72]:
result

,cand_nm,contbr_occupation,contb_receipt_amt,file_num
0,"Bachmann, Michelle",100% DISABLED VETERAN,1869.50,6807894
1,"Bachmann, Michelle",100% DISABLED VIETNAM VETERAN,236.25,2260398
2,"Bachmann, Michelle",A/C AND HEAT,250.00,749016
3,"Bachmann, Michelle",ACADEMIC EMPLOYMENT SPECIALIST,25.00,762366
4,"Bachmann, Michelle",ACCOUNT,50.00,762366
5,"Bachmann, Michelle",ACCOUNT ANALYST,200.00,749016
6,"Bachmann, Michelle",ACCOUNT EXECUTIVE,100.00,762366
7,"Bachmann, Michelle",ACCOUNT MANAGER,230.00,1524732
8,"Bachmann, Michelle",ACCOUNTANT,12979.00,49048913
9,"Bachmann, Michelle",ACCOUNTANT TRAINER,250.00,736307
10,"Bachmann, Michelle",ACCOUNTING,350.00,1511382
11,"Bachmann, Michelle",ACCOUNTING MANAGER,50.00,1511382
12,"Bachmann, Michelle",ACCOUNTING SPECIALIST,250.00,736166
13,"Bachmann, Michelle",ACCOUNTING SUPERVISOR,125.00,762366
14,"Bachmann, Michelle",ACCOUNTING/AUDITING,700.00,1498673
15,"Bachmann, Michelle",ACTIVE DUTY MILITARY,125.00,762366
16,"Bachmann, Michelle",ACTRESS,601.00,4534146
17,"Bachmann, Michelle",ACTUARY,1050.00,1498673
18,"Bachmann, Michelle",AD EXEC,401.00,2996064
19,"Bachmann, Michelle",ADJURET ASST. PROF,31.00,749016
20,"Bachmann, Michelle",ADJUSTER,250.00,736307
21,"Bachmann, Michelle",ADMIN. ASSISTANT,250.00,736307
22,"Bachmann, Michelle",ADMINISNATIVE ASST,125.00,749016
23,"Bachmann, Michelle",ADMINISTRATION,1245.00,9082142
24,"Bachmann, Michelle",ADMINISTRATIVE ASSISTANT,300.00,736307
25,"Bachmann, Michelle",ADMINISTRATIVE EXECUTIVE,200.00,762366
26,"Bachmann, Michelle",ADMINISTRATIVE LAW JUDGE,575.00,3049464
27,"Bachmann, Michelle",ADMINISTRATIVE MED PRAC,100.00,762366
28,"Bachmann, Michelle",ADMINISTRATOR,4587.00,11289281
29,"Bachmann, Michelle",ADMINSTRATOR,300.00,3811830
...,...,...,...,...
40131,"Santorum, Rick",WEB COMM. MANAGER,1000.00,763229
40132,"Santorum, Rick",WEB DESIGN,500.00,767129
40133,"Santorum, Rick",WEB DESIGNER,235.00,767129
40134,"Santorum, Rick",WEBMASTER,250.00,767129
40135,"Santorum, Rick",WELD ENGINEER,1000.00,763229
40136,"Santorum, Rick",WELDER,250.00,767129
40137,"Santorum, Rick",WELL BEING,250.00,763255
40138,"Santorum, Rick",WELL BEING COORDINATOR,300.00,2301387
40139,"Santorum, Rick",WELLBORN CABINET INC.,500.00,763229
40140,"Santorum, Rick",WHEATON COLLEGE (IL) STUDENT,250.00,767129
40141,"Santorum, Rick",WHOLESALE MFG,400.00,2289765
40142,"Santorum, Rick",WIDOW,80.00,1534258
40143,"Santorum, Rick",WIFE AND MOTHER,1500.00,3831771
40144,"Santorum, Rick",WIFE AND MOTHER (AT HOME),100.00,767129
40145,"Santorum, Rick",WIFE MOTHER TEACHER,1000.00,767129
40146,"Santorum, Rick",WILDLIFE REFUGE MANAGER,200.00,767129
40147,"Santorum, Rick",WIND FARM DEVELOPER,400.00,3068516
40148,"Santorum, Rick",WINDOW CLEANER,85.00,1534258
40149,"Santorum, Rick",WINERY,300.00,1534258
40150,"Santorum, Rick",WIRELESS NETWORK ENGINEER,220.15,2301387
40151,"Santorum, Rick",WITHHELD,1000.00,763255
40152,"Santorum, Rick",WNG,700.00,2301387
40153,"Santorum, Rick",WORKER II,300.00,767129
40154,"Santorum, Rick",WRITER,4894.55,36771830
40155,"Santorum, Rick",WRITER ACTIVIST,1112.00,1534258
40156,"Santorum, Rick",WRITER EDITOR,250.00,2301387
40157,"Santorum, Rick",WRITER/ACCOUNT EXEC,500.00,763229
40158,"Santorum, Rick",WRITER/JOURNALIST,250.00,767129
40159,"Santorum, Rick",WRITER/LAWYER,300.00,767129
40160,"Santorum, Rick",YOUTH MINISTER,250.00,767129

In [86]:
# We have so far aggregated total amount donated to each political party by occupation (the first groupby).
# Additional groupby let us split them up by candidate, sort them in descending order by total amount donated and take the top 5.
def top5_donors(group):
    return group.sort_index(by='contb_receipt_amt')[-5:]
# top5_donors(result)
r = result.groupby('cand_nm').apply(top5_donors)   
r.sort('contb_receipt_amt', ascending=False).head(5) # The retired donated the most to Barack Obama.

r.sort('file_num', ascending=False).head(5)

/home/vagrant/miniconda2/envs/jupyterlab/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
/home/vagrant/miniconda2/envs/jupyterlab/lib/python2.7/site-packages/ipykernel/__main__.py:7: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/vagrant/miniconda2/envs/jupyterlab/lib/python2.7/site-packages/ipykernel/__main__.py:9: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                           cand_nm      contbr_occupation  contb_receipt_amt  \
cand_nm
Obama, Barack 18857  Obama, Barack                RETIRED        15086766.92
              7087   Obama, Barack               ATTORNEY         7112343.35
              13523  Obama, Barack  INFORMATION REQUESTED         2647247.90
Romney, Mitt  37910   Romney, Mitt                RETIRED         6483596.24
Paul, Ron     28455      Paul, Ron                RETIRED         1799513.76

                        file_num
cand_nm
Obama, Barack 18857  56651749795
              7087   10125124417
              13523   9953639519
Romney, Mitt  37910   9766405414
Paul, Ron     28455   7168673970

In [ ]:
df._data   # Internal data structure. The back data frame. Having hierarchical indexing medicates a lot of the need for higher dimensional objects (because they're very sparse).

In [ ]:
# Time Series for financial data will be improved next.